"""Vendor the brand v2 typefaces into brand/fonts/ (run from the Instrumenta repository root).

    python3 brand/scripts/vendor-fonts.py

Fraunces (display), Commissioner (interface) and Spline Sans Mono (code), as variable WOFF2 in the
Latin and Latin Extended subsets, with their SIL Open Font License texts. Pages load
brand/fonts/fonts.css; nothing loads a font from a CDN, which the build audit forbids.
"""

import re
import urllib.request
from pathlib import Path

FONTS = Path(__file__).resolve().parents[1] / "fonts"
CSS_URL = ("https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,100..900,0..100,0..1"
           "&family=Commissioner:FLAR,VOLM,slnt,wght@0..100,0..100,-12..0,100..900"
           "&family=Spline+Sans+Mono:wght@300..700&display=swap")
LICENCES = {"fraunces": "fraunces", "commissioner": "commissioner", "splinesansmono": "splinesansmono"}
AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36"


def fetch(url: str) -> bytes:
    return urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": AGENT}), timeout=30).read()


def main() -> None:
    FONTS.mkdir(parents=True, exist_ok=True)
    css = fetch(CSS_URL).decode()
    out = ["/* Brand v2 type, vendored so no page loads a font from a CDN. All three are SIL Open Font\n"
           "   License 1.1; the licence texts sit beside the files. Generated by\n"
           "   brand/scripts/vendor-fonts.py. */\n"]
    for subset, face in re.findall(r"/\* ([\w-]+) \*/\s*(@font-face \{[^}]+\})", css):
        if subset not in ("latin", "latin-ext"):
            continue
        family = re.search(r"font-family: '([^']+)'", face).group(1)
        style = re.search(r"font-style: (\w+)", face).group(1)
        url = re.search(r"url\((https://[^)]+)\)", face).group(1)
        name = f"{family.lower().replace(' ', '-')}-{style}-{subset}.woff2"
        (FONTS / name).write_bytes(fetch(url))
        out.append(f"/* {family} {style}, {subset} */\n{face.replace(url, name)}\n")
    (FONTS / "fonts.css").write_text("\n".join(out), encoding="utf-8")
    for local, remote in LICENCES.items():
        (FONTS / f"OFL-{local}.txt").write_bytes(fetch(f"https://raw.githubusercontent.com/google/fonts/main/ofl/{remote}/OFL.txt"))
    print(f"Vendored {len(out) - 1} faces into {FONTS}")


if __name__ == "__main__":
    main()
